version: "2.1"

services: 
  elasticsearch:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    user: elasticsearch
    volumes:
      - ./docker/elastic:/init/
    entrypoint: /init/entrypoint
    command: /usr/share/elasticsearch/bin/elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    expose:
      - 9200
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.6.0
    ports:
      - 5601:5601
    expose:
      - 5601
    depends_on:
      - elasticsearch
      
